### PR TITLE
New asgs

### PR DESCRIPTION
**Pull request by stevage**

### CODE REVIEW

**Comment by tobybellwood** [comment]
I'm not loving the scale-dependent feature selection that appears to be the default?  Maybe we should be using http://censusdata.abs.gov.au/arcgis/rest/services/ASGS2016/ASGS2016BoundariesOnline/MapServer instead as complete coverages?

**Comment by stevage** [comment]
Sorry, can you break that down for me a bit? :)

**Comment by tobybellwood** [comment]
If you load the sa1s whilst at national scale, it only loads the ones larger than 100k hectares, and as you zoom in, it progressively adds the SA1s with smaller areas.  Look at Sydney as you go, it leaves strangely empty holes until you zoom all the way in.  The second MapServer link has the complete coverage at all zoom levels.

**Comment by stevage** [comment]
Ok, thanks @tobybellwood. They do work better - although they're all grey. :/

**Comment by kring** [comment]
@stevage can you merge master into this?  There are conflicts.

**Comment by stevage** [comment]
​Done - just the standard build/nm.json conflict.

**Pull request merged**
