### PR TITLE
Remove QLD Administrative Boundaries group

### PR DESCRIPTION
**Pull request by kring**
The MapServer no longer exists.

### CODE REVIEW

**Comment by kring** [comment]
@tobybellwood if you want to review and merge this I'll push the change to the live site.

**Comment by kring** [comment]
You can test it with http://nationalmap.gov.au/#clean&https://raw.githubusercontent.com/TerriaJS/NationalMap-Catalog/84f02b234011aaf5d09495091282a3a0ab3226b7/build/nm.json

**Comment by tobybellwood** [comment]
Looks like they've had a re-org of their folders https://geospatial.information.qld.gov.au/ArcGIS/rest/services/QLD/

Happy for you to go ahead, merge and push

**Comment by kring** [comment]
Yeah, no obvious admin boundaries there anymore though, right?  Or did I miss it?

**Comment by tobybellwood** [comment]
nothing obvious - we'll work with QLD to work out what we need to put in for them.

**Comment by kring** [comment]
This change is live on nationalmap.gov.au now.

**Pull request merged**
